to_file = {
    # Images
    "png": "Image",
    "jpg": "Image",
    "jpeg": "Image",
    "gif": "Image",
    "bmp": "Image",
    "tiff": "Image",
    "svg": "Image",
    "ico": "Image",
    "webp": "Image",
    # Audio
    "mp3": "Audio",
    "wav": "Audio",
    "ogg": "Audio",
    "wma": "Audio",
    "flac": "Audio",
    "aac": "Audio",
    "m4a": "Audio",
    # Video
    "mp4": "Video",
    "avi": "Video",
    "mkv": "Video",
    "mov": "Video",
    "wmv": "Video",
    "flv": "Video",
    "webm": "Video",
    "3gp": "Video",
    # Archives
    "rar": "Archive",
    "zip": "Archive",
    "7z": "Archive",
    "tar": "Archive",
    "gz": "Archive",
    "bz2": "Archive",
    "xz": "Archive",
    # Executables
    "exe": "Executable",
    "msi": "Executable",
    "jar": "Executable",
    # Documents
    "csv": "Document",
    "json": "Document",
    "xml": "Document",
    "pdf": "Document",
    "doc": "Document",
    "docx": "Document",
    "xls": "Document",
    "xlsx": "Document",
    "ppt": "Document",
    "pptx": "Document",
    "txt": "Document",
    "rtf": "Document",
    "log": "Document",
    "md": "Document",
    "html": "Document",
    "htm": "Document",
    # Code
    "js": "Code",
    "py": "Code",
    "java": "Code",
    "c": "Code",
    "cpp": "Code",
    "h": "Code",
    "sql": "Code",
    "php": "Code",
    "asp": "Code",
    "jsp": "Code",
    "bat": "Code",
    "sh": "Code",
    "css": "Code",
    "xml": "Code",
    "ini": "Code",
    "cfg": "Code",
    # Fonts
    "ttf": "Font",
    "otf": "Font",
    "woff": "Font",
    "woff2": "Font",
    # Compressed
    "gz": "Compressed",
    "bz2": "Compressed",
    "xz": "Compressed",
    "z": "Compressed",
    # Database
    "sqlite": "Database",
    "db": "Database",
    # Miscellaneous
    "dat": "Miscellaneous",
    "conf": "Miscellaneous",
    "dll": "Miscellaneous",
    "iso": "Miscellaneous",
    "bin": "Miscellaneous",
    "pdb": "Miscellaneous",
    "rpm": "Miscellaneous",
    "deb": "Miscellaneous",
    # 3D Modeling and Printing
    "f3d": "3D Model",
    "stl": "3D Model",
    "obj": "3D Model",
    "blend": "3D Model",
    "fbx": "3D Model",
    "dae": "3D Model",
    "step": "3D Model",
    "iges": "3D Model",
    "3dm": "3D Model",
    "amf": "3D Model",
    "gcode": "G-code",
    # JSON
    "json": "JSON Data",
    "yml": "YAML Data",
    # Certs
    "crt": "Certs",
    "pem": "Certs",
    # Fl studio
    "flp": "FL Studio Project",
    "midi": "MIDI Data"
}
